VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no

KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = azoteq_iqs5xx
